//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
namespace WebCamWindowsClient.WebCamService
{


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName = "WebCamService.IWebCamService")]
    public interface IWebCamService
    {

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IWebCamService/getWaveMD5", ReplyAction = "http://tempuri.org/IWebCamService/getWaveMD5Response")]
        string getWaveMD5();

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IWebCamService/arduinoStart", ReplyAction = "http://tempuri.org/IWebCamService/arduinoStartResponse")]
        void arduinoStart(string loginName, string aPort, string lastLabID, string lastDevID, string userPermission, ref DateTime date);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IWebCamService/sendSerialData", ReplyAction = "http://tempuri.org/IWebCamService/sendSerialDataResponse")]
        void sendSerialData(string loginName, string serialText, ref DateTime date);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IWebCamService/getNewSerialData", ReplyAction = "http://tempuri.org/IWebCamService/getNewSerialDataResponse")]
        string getNewSerialData(string loginName, ref DateTime lastDate);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IWebCamService/getArduinoUserList", ReplyAction = "http://tempuri.org/IWebCamService/getArduinoUserListResponse")]
        string getArduinoUserList(string loginName);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IWebCamService/arduinoCompiling", ReplyAction = "http://tempuri.org/IWebCamService/arduinoCompilingResponse")]
        string arduinoCompiling(string sourceCode);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IWebCamService/arduinoUploading", ReplyAction = "http://tempuri.org/IWebCamService/arduinoUploadingResponse")]
        string arduinoUploading();

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IWebCamService/stop_arduino", ReplyAction = "http://tempuri.org/IWebCamService/stop_arduinoResponse")]
        void stop_arduino(string loginName);
        
        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IWebCamService/chatStart", ReplyAction = "http://tempuri.org/IWebCamService/chatStartResponse")]
        void chatStart(string loginName, ref DateTime date);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IWebCamService/setNewChatLine", ReplyAction = "http://tempuri.org/IWebCamService/setNewChatLineResponse")]
        void setNewChatLine(string loginName, string lineChat, ref DateTime date);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IWebCamService/getNewChatLine", ReplyAction = "http://tempuri.org/IWebCamService/getNewChatLineResponse")]
        string getNewChatLine(string loginName, ref DateTime date);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IWebCamService/getNewUserList", ReplyAction = "http://tempuri.org/IWebCamService/getNewUserListResponse")]
        string getNewUserList();

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IWebCamService/stop_Chat", ReplyAction = "http://tempuri.org/IWebCamService/stop_ChatResponse")]
        void stop_Chat(string loginName);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IWebCamService/getWebCamImage", ReplyAction = "http://tempuri.org/IWebCamService/getWebCamImageResponse")]
        System.IO.Stream getWebCamImage(string loginName);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IWebCamService/getMicBuffer", ReplyAction = "http://tempuri.org/IWebCamService/getMicBufferResponse")]
        byte[] getMicBuffer();

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IWebCamService/micStart", ReplyAction = "http://tempuri.org/IWebCamService/micStartResponse")]
        void micStart(int mValue);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IWebCamService/stop_Mic", ReplyAction = "http://tempuri.org/IWebCamService/stop_MicResponse")]
        void stop_Mic();

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IWebCamService/Record", ReplyAction = "http://tempuri.org/IWebCamService/RecordResponse")]
        void Record(string loginName, string cValue, string cName, string lID, string cID);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IWebCamService/stop_record", ReplyAction = "http://tempuri.org/IWebCamService/stop_recordResponse")]
        void stop_record(string loginName);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IWebCamService/waveMicBuffer", ReplyAction = "http://tempuri.org/IWebCamService/waveMicBufferResponse")]
        int waveMicBuffer();

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IWebCamService/CamerasNr", ReplyAction = "http://tempuri.org/IWebCamService/CamerasNrResponse")]
        int CamerasNr();

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IWebCamService/CamerasNames", ReplyAction = "http://tempuri.org/IWebCamService/CamerasNamesResponse")]
        string[] CamerasNames();

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IWebCamService/CamerasValues", ReplyAction = "http://tempuri.org/IWebCamService/CamerasValuesResponse")]
        string[] CamerasValues();
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWebCamServiceChannel : WebCamWindowsClient.WebCamService.IWebCamService, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebCamServiceClient : System.ServiceModel.ClientBase<WebCamWindowsClient.WebCamService.IWebCamService>, WebCamWindowsClient.WebCamService.IWebCamService
    {

        public WebCamServiceClient()
        {
        }

        public WebCamServiceClient(string endpointConfigurationName) :
            base(endpointConfigurationName)
        {
        }

        public WebCamServiceClient(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public WebCamServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public WebCamServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
        {
        }

        public string getWaveMD5()
        {
            return base.Channel.getWaveMD5();
        }

        public void arduinoStart(string loginName, string aPort, string lastLabID, string lastDevID, string userPermission, ref DateTime date)
        {
            base.Channel.arduinoStart(loginName, aPort, lastLabID, lastDevID, userPermission, ref date);
        }

        public string getArduinoUserList(string loginName)
        {
            return base.Channel.getArduinoUserList(loginName);
        }

        public void sendSerialData(string loginName, string serialText, ref DateTime date)
        {
            base.Channel.sendSerialData(loginName, serialText, ref date);
        }

        public string getNewSerialData(string loginName, ref DateTime lastDate)
        {
            return base.Channel.getNewSerialData(loginName, ref lastDate);
        }

        public string arduinoCompiling(string sourceCode)
        {
            return base.Channel.arduinoCompiling(sourceCode);
        }

        public string arduinoUploading()
        {
            return base.Channel.arduinoUploading();
        }

        public void stop_arduino(string loginName)
        {
            base.Channel.stop_arduino(loginName);
        }

        public void chatStart(string loginName, ref DateTime date)
        {
            base.Channel.chatStart(loginName, ref date);
        }

        public void setNewChatLine(string loginName, string lineChat, ref DateTime date)
        {
            base.Channel.setNewChatLine(loginName, lineChat, ref date);
        }

        public string getNewChatLine(string loginName, ref DateTime date)
        {
            return base.Channel.getNewChatLine(loginName, ref date);
        }

        public string getNewUserList()
        {
            return base.Channel.getNewUserList();
        }

        public void stop_Chat(string loginName)
        {
            base.Channel.stop_Chat(loginName);
        }

        public byte[] getMicBuffer()
        {
            return base.Channel.getMicBuffer();
        }

        public void micStart(int mValue)
        {
            base.Channel.micStart(mValue);
        }

        public void stop_Mic()
        {
            base.Channel.stop_Mic();
        }

        public System.IO.Stream getWebCamImage(string loginName)
        {
            return base.Channel.getWebCamImage(loginName);
        }

        public void Record(string loginName, string cValue, string cName, string lID, string cID)
        {
            base.Channel.Record(loginName, cValue, cName, lID, cID);
        }

        public void stop_record(string loginName)
        {
            base.Channel.stop_record(loginName);
        }

        public int waveMicBuffer()
        {
            return base.Channel.waveMicBuffer();
        }

        public int CamerasNr()
        {
            return base.Channel.CamerasNr();
        }

        public string[] CamerasNames()
        {
            return base.Channel.CamerasNames();
        }

        public string[] CamerasValues()
        {
            return base.Channel.CamerasValues();
        }
    }
}
